= BambooSMTP Sandbox

image:https://github.com/fewlinesco/bamboo_smtp-playground/workflows/Continuous%20Integration/badge.svg?branch=master&event=push[Continuous Integration]

== Description

This project aims to be a sandbox for developers testing https://github.com/fewlinesco/bamboo_smtp[BambooSMTP].

== Installation

Once you cloned this project, heads up to `mix.exs` to set the desired version of BambooSMTP.

[source, elixir]
----
# By default, we target the current release.
defp deps do
  [{:bamboo_smtp, "~> 3.1.1"}]
end

# You might want to target a local version on your computer.
defp deps do
  [{:bamboo_smtp, path: "../path/to/bamboo_smtp"}]
end
----

You will need to set some values as environment variables.

[source, bash]
----
# Create a new file for env vars (based on our sample).
cp .env_vars.sample .env_vars
----

Then, set the following values in `.env_vars`:

- `EMAIL_TO`: The email address you want to send an email.
- `EMAIL_FROM`: The email address that will send the email.

You will find the SMTP configuration options below those values.

If you don't already have a SMTP server ready, the easiest way is to use <<anchor-google-smtp, Google Portable SMTP>>.

=== [[anchor-google-smtp]]Using Google Portable SMTP

Requirements:

- You should own a Google account (and so, a Gmail address).
- You should allow https://support.google.com/mail/answer/7126229?hl=en[IMAP transfert].
- If you have https://en.wikipedia.org/wiki/Multi-factor_authentication[2FA] enabled: you should manually https://support.google.com/accounts/answer/185833?hl=en[create an application password] and use it as `SMTP_PASSWORD`.

Once you have all the requirements, you can set the following values:

[%header,cols=2*]
|===
| VAR NAME
| VALUE

| SMTP_SERVER
| smtp.gmail.com

| SMTP_HOSTNAME
| [YOU CAN PUT ANYTHING HERE]

| SMTP_PORT
| 465

| SMTP_USERNAME
| [YOUR GMAIL ADDRESS]

| SMTP_PASSWORD
| [YOUR GMAIL PASSWORD]
|===

== Usage

The application is intended to be used through `iex`.

[source, bash]
----
iex -S mix
----

Once inside `iex`, you will have access to some functions such as:

[source, elixir]
----
# Send a basic email with some default values as subject and text body.
BambooSMTPSandbox.Sender.send_sample_email()

# Send a basic email like above but with some attachments.
BambooSMTPSandbox.Sender.send_sample_email_with_attachments()
----

== Code of Conduct

By participating in this project, you agree to abide by its link:CODE_OF_CONDUCT.adoc[CODE OF CONDUCT].

== Contributing

You can see the specific link:CONTRIBUTING.adoc[CONTRIBUTING] guide.

== License

Bamboo SMTPAdapter is released under https://opensource.org/licenses/MIT[The MIT License (MIT)].
